version: "3.7"

services:
  backend:
    image: python/backend
    build:
      context: ./app/python_app/
    networks:
      - apicollider-network
    volumes:
      - ./app/python_app:/usr/src/app/public
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/certbot
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/react_app/build/:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/certbot
    networks:
      - apicollider-network
    depends_on:
      - backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    ports:
      - 80:80
      - "443:443"
  mongo:
    image: mongo
    networks:
      - apicollider-network
    volumes:
      - ./data/db:/data/db
    # ports:
    # - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    #   MONGO_INITDB_DATABASE: apicollider

networks:
  apicollider-network:
    driver: bridge
